import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/styles/global.scss";

import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import "@mantine/charts/styles.css";
import "@mantine/code-highlight/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/dropzone/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/nprogress/styles.css";
import "@mantine/spotlight/styles.css";
import "@mantine/tiptap/styles.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";

import projectName from "@/styles/theme";

import Layout from "@/layouts";
import Partial from "@/partials";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body className={inter.className}>
				<MantineProvider theme={projectName}>
					<Layout.Body nav={<Partial.Navbar.Main />} footer={<footer>footer</footer>}>
						<main>{children}</main>
					</Layout.Body>
				</MantineProvider>
			</body>
		</html>
	);
}
