const icons = {
	browser: {
		brave: "/icons/browser/icons8-brave-web-browser.svg",
		chrome: "/icons/browser/icons8-chrome.svg",
		duckduckgo: "/icons/browser/icons8-duckduckgo.svg",
		explorer: "/icons/browser/icons8-internet-explorer.svg",
		opera: "/icons/browser/icons8-opera.svg",
		safari: "/icons/browser/icons8-safari.svg",
	},

	os: {
		android: "/icons/os/icons8-android-os.svg",
		fedora: "/icons/os/icons8-fedora-96.png",
		ubuntu: "/icons/os/icons8-ubuntu-96.png",
		windows10: "/icons/os/icons8-windows-10.svg",
		zorin: "/icons/os/icons8-zorin.svg",
	},

	search: {
		bing: "/icons/search/icons8-bing.svg",
		duckduckgo: "/icons/search/icons8-duckduckgo.svg",
		google: "/icons/search/icons8-google.svg",
		yahoo: "/icons/search/icons8-yahoo.svg",
	},

	social: {
		behance: "/icons/social/icons8-behance.svg",
		credly: "/icons/social/icons8-credly.svg",
		dribble: "/icons/social/icons8-dribble.svg",
		facebook: "/icons/social/icons8-facebook.svg",
		fiverr: "/icons/social/icons8-fiverr.svg",
		instagram: "/icons/social/icons8-instagram.svg",
		linkedin: "/icons/social/icons8-linkedin.svg",
		medium: "/icons/social/icons8-medium.svg",
		twitter: "/icons/social/icons8-twitter.svg",
		whatsapp: "/icons/social/icons8-whatsapp.svg",
	},

	software: {
		dreamweaver: "/icons/software/icons8-adobe-dreamweaver.svg",
		illustrator: "/icons/software/icons8-adobe-illustrator.svg",
		photoshop: "/icons/software/icons8-adobe-photoshop.svg",
		canva: "/icons/software/icons8-canva.svg",
		figma: "/icons/software/icons8-figma.svg",
		onenote: "/icons/software/icons8-microsoft-onenote-2019.svg",
		teams: "/icons/software/icons8-microsoft-teams-2019.svg",
		notion: "/icons/software/icons8-notion.svg",
		obsidian: "/icons/software/icons8-obsidian.svg",
		outlook: "/icons/software/icons8-outlook.svg",
		ticktick: "/icons/software/icons8-tick-tick.svg",
		code: "/icons/software/icons8-visual-studio-code-2019.svg",
		visualstudio: "/icons/software/icons8-visual-studio.svg",
		intellij: "/icons/software/icons8-intellij-idea.svg",
		webstorm: "/icons/software/icons8-webstorm.svg",
		github: "/icons/software/icons8-github.svg",
		sublime: "/icons/software/icons8-sublime.svg",
	},

	tools: {
		bootstrap: "/icons/tools/icons8-bootstrap.svg",
		chakraui: "/icons/tools/icons8-chakra-ui.svg",
		css3: "/icons/tools/icons8-css3.svg",
		eslint: "/icons/tools/icons8-eslint.svg",
		expressjs: "/icons/tools/icons8-express-js.svg",
		git: "/icons/tools/icons8-git.svg",
		html5: "/icons/tools/icons8-html-5.svg",
		javascript: "/icons/tools/icons8-javascript.svg",
		mongodb: "/icons/tools/icons8-mongodb.svg",
		mongoose: "/icons/tools/icons8-mongoose.svg",
		mysql: "/icons/tools/icons8-mysql.svg",
		nextjs: "/icons/tools/icons8-next-js.svg",
		nodejs: "/icons/tools/icons8-node-js.svg",
		postgresql: "/icons/tools/icons8-postgresql.svg",
		react: "/icons/tools/icons8-react.svg",
		sass: "/icons/tools/icons8-sass.svg",
		tailwind: "/icons/tools/icons8-tailwind.svg",
		typescript: "/icons/tools/icons8-typescript.svg",
		vite: "/icons/tools/icons8-vite.svg",
		sequelize: "/icons/tools/sequelize-svgrepo-com.svg",
		mantine: "/icons/tools/mantine-logo.svg",
		claude: "/icons/tools/icons8-claude.svg",
	},

	other: {
		apple: "/icons/icons8-apple.svg",
		claude: "/icons/icons8-claude.svg",
		microsoft: "/icons/icons8-microsoft.svg",
		email: "/icons/icons8-email.png",
	},
};

export default icons;
